### ISSUE TITLE
项目运行后报错，提示安全性相关问题

### ISSUE THREAD

**Issue by JacolMark** [Hxy1992/MapDownload#11]
**Describe the bug**
项目运行后报错，提示安全性相关问题
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' blob:".

Windows 10 家庭中文版    22H2
操作系统内部版本  19045.3324

nodeJS Version : 10.15.1  /  16.17.0
npm Version :  6.4.1 / 8.15.0

![error](https://github.com/Hxy1992/MapDownload/assets/49934438/508d137a-281a-433f-9dc3-d791972273c2)

**Comment by Hxy1992** [comment]
Electron 应用程序在 Windows 家庭版中可能会受到一些 Content Security Policy（CSP）的限制。这是因为 Windows 家庭版对于底层浏览器引擎的功能和安全设置有一些限制。

在 Windows 家庭版中，CSP 的默认设置可能会更严格，并且可能不允许某些特定的脚本或内容加载。这可能导致 Electron 应用程序在某些安全设置较高的环境中出现问题，例如无法加载必要的脚本文件或资源。

为了解决这个问题，你可以尝试以下方法：

1. 更新操作系统：确保你的 Windows 家庭版安装了最新的更新和补丁。有时，Microsoft 可能会通过更新来放宽某些 CSP 设置的限制。
2. 配置 Electron 的 CSP 策略：在你的 Electron 应用程序中，你可以尝试自定义 CSP 策略来适应 Windows 家庭版的限制。你可以通过在应用程序的主进程代码中使用 session 对象的 setCSP 方法来设置自定义的 CSP 策略。

例如：
`const { app } = require('electron');

app.on('ready', () => {
  // 获取当前的会话对象
  const session = require('electron').session;

  // 设置自定义的 CSP 策略
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': ['default-src \'self\'']
      }
    });
  });
});
`
上述代码将设置默认源（default-src）为当前页面的源（'self'）。你可以根据自己的需求调整 CSP 策略。
请注意，以上方法可能需要你在 Electron 应用程序中进行相应的代码更改。另外，由于 CSP 设置涉及到安全性和浏览器限制方面的问题，我建议在实际应用中进行充分的测试和验证，以确保符合你的安全需求和目标环境。
