### ISSUE TITLE
build 启动后出现 Cannot read properties of undefined (reading 'ipcRenderer')

### ISSUE THREAD

**Issue by BoneBee** [Hxy1992/MapDownload#14]
![image](https://github.com/Hxy1992/MapDownload/assets/48782834/568b7a57-6305-434d-a72d-d3e642d5b8c4)

**Comment by Hxy1992** [comment]
试一下：
V0.42版本win-unpacked压缩包 百度网盘链接：https://pan.baidu.com/s/1M12KnC8bIvyHo3ik3hxy9A   提取码：9986
