### ISSUE TITLE
谷歌地图无法加载

### ISSUE THREAD

**Issue by chunsan** [Hxy1992/MapDownload#23]
![微信截图_20240801160356](https://github.com/user-attachments/assets/cb4b8c8b-fa7c-41a9-bbc0-3c5f55b13422)

**Comment by JOKEr20230301** [comment]
你好，我也遇到这个问题了，可以请教一下你是怎么解决的吗

**Comment by Hxy1992** [comment]
v0.45已修改谷歌服务域名：
新域名为 gac-geo.googlecnapps.club
