### ISSUE TITLE
下载时软件会卡住，下载后，只有文件夹没有图片。

### ISSUE THREAD

**Issue by chunkchen** [Hxy1992/MapDownload#4]
**Describe the bug**
选择下载区域，点击下载，软件会卡住，然后只把文件夹下载了，没有图片。
请问作者这个有遇到过么？

**Comment by Hxy1992** [comment]
@chunkchen 无法复现这个问题，麻烦提供详细一点的信息。
下面是正常下载的结果截图：
![image](https://user-images.githubusercontent.com/14800641/189024499-dead7838-3d33-46f8-942f-acd88cfcca13.png)


> **Describe the bug** 选择下载区域，点击下载，软件会卡住，然后只把文件夹下载了，没有图片。 请问作者这个有遇到过么？

**Comment by chunkchen** [comment]
试了几次，发现选择较小的层级可以下载。我选择了14-18。点击下载后，UI卡死，打开资源管理器cpu100%。时间一长程序自行退出。
我单独试了一下最小和最大都选择了18，现象一样。
您试试，看能否帮忙优化一下。
![map-download_8E7cqruSBf](https://user-images.githubusercontent.com/794836/189349134-8a6d4678-6416-4279-beee-04601d6fad12.jpg)
<img width="334" alt="explorer_xQrIZSx9K2" src="https://user-images.githubusercontent.com/794836/189349160-c0ae7466-74a6-48f9-8a99-c829634102a8.png">

**Comment by Hxy1992** [comment]
了解了，有空排查一下

**Comment by Hxy1992** [comment]
已解决
