### ISSUE TITLE
osm地图无法下载了

### ISSUE THREAD

**Issue by leungMr** [Hxy1992/MapDownload#6]
下载进度一直是0，希望大佬修复一下

**Comment by Hxy1992** [comment]
原osm地图地址访问不了，已更换新地址

**Comment by leungMr** [comment]
感谢大佬的及时修复，我安装了最新的发布版本，确实已经可用了！
但是发现新地址和旧地址，不是同一个数据源，不过影响也不大，还要啥自行车/。

----

一个建议，有没有可能增加一些wgs84的地图源，那种没有token限制的，国内可用的中文地图，哈哈~
